const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/user.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "MC Pay Test",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3010",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Personal Finance",
            "description": "API for users in the system"
        }
    ],
    definitions: {
        User: {
            name: 'user-test-1',
            username: 'user-test-1',
            password: 'usertest123'
        },
        UserAdd: {
            name: 'user-test-1',
            username: 'user-test-1',
            password: 'usertest123',
            password_confirmation: 'usertest123',
            balance:10000
        },
        UserEdit: {
            id:2,
            name: 'user-test-1',
            username: 'user-test-1',
            password: 'usertest123',
            balance:10000
        },
        UserLogin: {
            username: 'user-test-1',
            password: 'usertest123'
        },
        Users: {
            "type": "array",
            "$ref": "#/definitions/User"
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})
